apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqldeployment
  
spec:

  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: secret-deployment
        image: mysql:5.6
        ports:
        - containerPort: 3306
        env:
        - name : MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
               name: secret 
               key: password